apiVersion: template.openshift.io/v1
kind: Template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true

objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="${PREFIX}metabase-postgres")].port}
    name: ${PREFIX}metabase-postgres
  spec:
    ports:
    - name: ${PREFIX}metabase-postgres
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: ${PREFIX}metabase-postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

