apiVersion: template.openshift.io/v1
kind: Template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 20Gi

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${PREFIX}metabase-postgres
  spec:
    storageClassName: gluster-file-db
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}

