apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template


parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: Git tag of the metabase version
  displayName: Metabase version
  name: METABASE_VERSION
  required: true


objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${PREFIX}metabase-preview
  spec:
    replicas: 1
    selector:
      name: ${PREFIX}metabase-preview
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${PREFIX}metabase-preview
      spec:
        containers:
        - env:
          - name: MB_DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${PREFIX}metabase-postgres
          - name: MB_DB_PASS
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${PREFIX}metabase-postgres
          - name: MB_DB_DBNAME
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${PREFIX}metabase-postgres
          - name: MB_DB_TYPE
            value: postgres
          - name: MB_DB_PORT
            value: "5432"
          - name: MB_DB_HOST
            value: ${PREFIX}metabase-postgres
          - name: JAVA_TIMEZONE
            value: US/Pacific
          image: ${PREFIX}metabase:${METABASE_VERSION}
          imagePullPolicy: IfNotPresent
          name: ${PREFIX}metabase
          ports:
          - containerPort: 3000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
