apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true
  - description: Base64-encoded ggircs DB.
    displayName: Giircs DB
    name: METABASE_DB
    required: true
  - description: Base64-encoded ggircs user.
    displayName: Giircs user
    name: METABASE_USER
    required: true
  - description: Base64-encoded password for the ggircs user.
    displayName: Giircs Password
    name: METABASE_PASSWORD
    required: true

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        beta.kubernetes.io/os: linux
      name: ${PREFIX}metabase-postgres
    type: Opaque
    data:
      database-name: ${METABASE_DB}
      database-user: ${METABASE_USER}
      database-password: ${METABASE_PASSWORD}
