apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template
parameters:
- description: Version of PostgreSQL image to be used (10 for now).
  displayName: Version of PostgreSQL Image
  name: OC_PROJECT
  required: true
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true

objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${PREFIX}metabase-preview
  spec:
    host: metabase-preview-${OC_PROJECT}.pathfinder.gov.bc.ca
    port:
      targetPort: ${PREFIX}metabase-preview
    tls:
      termination: edge
    to:
      kind: Service
      name: ${PREFIX}metabase-preview
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - status: 'True'
        type: Admitted
      host: metabase-preview-${OC_PROJECT}.pathfinder.gov.bc.ca
      routerName: router
      wildcardPolicy: None

