apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template

parameters:
  - description: Openshift project name.
    displayName: Project
    name: OC_PROJECT
    required: true
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true
  - description: Suffix to append to the route host
    displayName: Route Suffix
    name: ROUTE_SUFFIX
    required: false

objects:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${PREFIX}metabase
    spec:
      host: cas-metabase${ROUTE_SUFFIX}.pathfinder.gov.bc.ca
      port:
        targetPort: ${PREFIX}metabase
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: ${PREFIX}metabase
        weight: 100
      wildcardPolicy: None
    status:
      ingress:
        - conditions:
            - status: "True"
              type: Admitted
          host: cas-metabase${ROUTE_SUFFIX}.pathfinder.gov.bc.ca
          routerName: router
          wildcardPolicy: None
